# Generated by Django 5.1.6 on 2025-03-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('moda', 'Moda'), ('belleza', 'Belleza'), ('fitness', 'Fitness y Salud'), ('viajes', 'Viajes'), ('comida', 'Comida'), ('tecnologia', 'Tecnología'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('otro', 'Otro')], max_length=20)),
                ('platforms', models.CharField(help_text='Plataformas separadas por comas (ej: Instagram, TikTok)', max_length=200)),
                ('audience_size', models.CharField(choices=[('micro', 'Micro (1K-10K seguidores)'), ('pequeno', 'Pequeño (10K-50K seguidores)'), ('medio', 'Medio (50K-100K seguidores)'), ('grande', 'Grande (100K-500K seguidores)'), ('macro', 'Macro (500K-1M seguidores)'), ('mega', 'Mega (1M+ seguidores)')], max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('tecnologia', 'Tecnología'), ('moda', 'Moda y Belleza'), ('alimentos', 'Alimentos y Bebidas'), ('salud', 'Salud y Bienestar'), ('viajes', 'Viajes y Turismo'), ('entretenimiento', 'Entretenimiento'), ('educacion', 'Educación'), ('otro', 'Otro')], max_length=20)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501+', '501+ empleados')], max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='profiles.profile')),
            ],
        ),
    ]
