# Generated by Django 5.1.6 on 2025-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, default='images/perritos.png', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
