# Generated by Django 5.1.6 on 2025-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_response_company_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
