# Generated by Django 5.1.6 on 2025-04-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='campaign_comments', to='campaigns.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='campaigns.campaign'),
        ),
    ]
